name: flutter_nodejs_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-129.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  http: ^1.1.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.1.1+1
  image_cropper: ^5.0.1
  cached_network_image: ^3.2.3
  cloudinary_public: ^0.23.1
  file_picker: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
